### ISSUE TITLE
[ISSUE] We are seeing a drop in events for iOS app 

### ISSUE THREAD

**Issue by ShobhitChourasia** [rudderlabs/rudder-sdk-ios#263]
Rudder version 1.6.0.
We are trying to compare the events sent from FE (via Rudder SDK for iOS) and that being triggered from BE for the same event and seeing a drop in FE events. Any know thing going on with this library?

**Comment by ShobhitChourasia** [comment]
Can we get a quick help with this?

**Comment by pallabmaiti** [comment]
When you upgrade to 1.6.0?

**Comment by ShobhitChourasia** [comment]
@pallabmaiti this upgrade is since May 2022.

**Comment by ShobhitChourasia** [comment]
We are seeing a difference of around 15% of events
FE events: 34k, BE events: 40 K
Is this expected?

**Comment by pallabmaiti** [comment]
That totally depends on the instrumentation of FE & BE. If you see an unexpected drop that might be due to other reasons, you can contact our Support team in [Slack](https://rudderstack.com/join-rudderstack-slack-community). Anyway, you should use the latest version of the SDK; 1.6.0 is the pretty old one.

**Comment by pallabmaiti** [comment]
Closing this issue for now. Feel free to reopen.
